### ISSUE TITLE
Credit `jbaiter/plugin.video.mubi`

### ISSUE THREAD

**Issue by jbaiter** [jamieu/plugin.video.mubi#3]
You used a lot of code from my old plugin in yours, especially in `resources.lib.mubi`.
Please be so kind and comply with the license and reference/credit the old project.

https://github.com/jbaiter/plugin.video.mubi

**Comment by jamieu** [comment]
Hi Johannes,

Apologies I previously had it hosted on my blog where I credited you and
only recently moved it to GitHub.
http://jamie.net/2014/07/xbmc-plugin-for-mubi/

Sorry, my oversight will update the code on GitHub so that it reference/credits
you / the old project.

Certianly wasn't intending to take credit for your part of the code, hope
you understand.

Jamie

**Comment by jbaiter** [comment]
No hard feelings, sorry if the original post came across as harsh. :hushed:
Thanks for updating the code so quickly! :heart:
