### ISSUE TITLE
Is is project dead?

### ISSUE THREAD

**Issue by gustavolinux** [jamieu/plugin.video.mubi#30]
Any chance to get it working again?

**Comment by jamieu** [comment]
Unfortunately the plugin worked by scraping the HTML of MUBI website (and later by unofficially sniffing/using the mobile API) to find the video streams, as no official API was available. But that required the plugin to be updated whenever the website itself was changed, which I didn't have the time to keep on top of myself. 

There has been some valiant contributions by others to keep the project going, but as of 2019 I think it's pretty much dead unless someone else comes along and wants to try and get it working again and/or MUBI release an official API.

**Comment by bjo81** [comment]
Scraping seems broken again, so it's a pitty there no API
`2020-09-06 15:57:29.369 T:140009437922880  NOTICE: Logging in with username: xyz and udid: 91943801513393196295
2020-09-06 15:57:29.881 T:140009437922880   ERROR: Login Failed
2020-09-06 15:57:30.433 T:140009437922880   ERROR: Failed to get country: <!DOCTYPE html>
                                            <html dir='ltr'>
                                            <head>
                                            <script>window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"326c84218a","applicationID":"8866134","transactionName":"cFZXEkRcX1kBQB4VWVRcSklTQUFaFm0FVQw=","queueTime":0,"applicationTime":18,"agent":""}</script>
`

**Comment by tiagovaz** [comment]
I recently tried to do some reverse-engeneering on the android app in an attempt to fix this issue. I used the nice [PCAP Remote ](https://egorovandreyrm.com/pcap-remote-tutorial/ )app with Wireshark. However, the sniffing should be done using a MITM technique to intercept HTTPS/TLS packets. The problem is that since Android 7, Google changed the default network security policy and third-part apps won't trust self-signed certificates. So, I couldn't bypass this restriction. One option could be using an old Android version, or a remote proxy which uses a trusted certificate. I didn't try those and I'm not sure if I'll have the time for that soon, even if I'd love to give some help to get this project back to life.
